### ISSUE TITLE
Having issues with Ruby/dalli-elasticache inside a Docker Container.

### ISSUE THREAD

**Issue by yicheung** [ktheory/dalli-elasticache#25]
Hi,  We are having problems with Passenger and RoR application running on Docker.  getting getaddrinfo: Name or service not known (SocketError) in nginx/errors.log, but all works on Ruby Console via 'bundle exec rails c'.  We are Running Ruby 2.3.1 on nginx/1.10.1 Phusion_Passenger/5.0.29. Also all networking and DNS resolution working fine on Docker container, tested with ping, nslookup and raw telnet to memcache server. Below are the additional errors below, don't see any issues with remote MySQL and Redis; any help would be greatly appreciated.
Thanks,

getaddrinfo: Name or service not known (SocketError)
  /usr/local/rvm/gems/ruby-2.3.1/gems/socksify-1.7.0/lib/socksify.rb:178:in `initialize'
  /usr/local/rvm/gems/ruby-2.3.1/gems/socksify-1.7.0/lib/socksify.rb:178:in `initialize'
  /usr/local/rvm/gems/ruby-2.3.1/gems/dalli-elasticache-0.2.0/lib/dalli/elasticache/auto_discovery/endpoint.rb:64:in `new'
  /usr/local/rvm/gems/ruby-2.3.1/gems/dalli-elasticache-0.2.0/lib/dalli/elasticache/auto_discovery/endpoint.rb:64:in `remote_command'
  /usr/local/rvm/gems/ruby-2.3.1/gems/dalli-elasticache-0.2.0/lib/dalli/elasticache/auto_discovery/endpoint.rb:47:in `get_stats_from_remote'
  /usr/local/rvm/gems/ruby-2.3.1/gems/dalli-elasticache-0.2.0/lib/dalli/elasticache/auto_discovery/endpoint.rb:27:in `stats'
  /usr/local/rvm/gems/ruby-2.3.1/gems/dalli-elasticache-0.2.0/lib/dalli/elasticache/auto_discovery/endpoint.rb:37:in `engine_version'
  /usr/local/rvm/gems/ruby-2.3.1/gems/dalli-elasticache-0.2.0/lib/dalli/elasticache/auto_discovery/endpoint.rb:52:in `get_config_from_remote'
  /usr/local/rvm/gems/ruby-2.3.1/gems/dalli-elasticache-0.2.0/lib/dalli/elasticache/auto_discovery/endpoint.rb:32:in `config'
  /usr/local/rvm/gems/ruby-2.3.1/gems/dalli-elasticache-0.2.0/lib/dalli/elasticache.rb:37:in `servers'
  /home/app/webapp/config/environments/production.rb:40:in `block in <top (required)>'

**Comment by yicheung** [comment]
Never mind, Looks likes it's nginx config issues with env variables.
